"""P1.T27 -- which HCLK input multiplexer a DHCE gates, as a function of the lane.

`P1.T26` measured the gate fuse of one block by an allocation-order sweep
(`n_dhce = 0..3` in the first-filled block) and could not separate two
hypotheses that the sweep confounds:

* **allocation order** -- the n-th DHCE of a block gates multiplexer `n`,
  whatever lane its clock is on; or
* **lane** -- a DHCE on lane `i` gates multiplexer `i` of its block.

They differ the moment a design puts a single DHCE on a lane other than 0.
`P1.T27` needs the answer because `nextpnr` picks the hardware DHCE by
matching a *routed wire* against the pip apicula records, so the recorded pip
has to be the one belonging to the lane the clock is actually on.

Method: one vendor compile per `(block, lane)` point, each a single DHCE
gating a single `CLKDIV` pinned to that lane by `INS_LOC`.  The block cell's
four gate fuses are computed from the chipdb alone
(`chipdb.gw5a_dhce_gate_fuses`); the measurement is which of the four the
vendor's bitstream sets.  Block 5 lane 0 is not re-run: batch `p1t38b-e2e`
already compiled exactly that design and its `.fs` is the sixth point.

    PYTHONPATH=<apicula worktree> python gate_probe.py --out-root ... --log ...
"""
import argparse
import json
import os
import shutil
import sys
import time

sys.path.insert(0, os.getcwd())
from fuzz.gw5ast138c.harness import oracle    # noqa: E402

DEVICE = "GW5AST-138C"
BATCH_ID = "p1t27-dhce-lane"

#: `(name, block cell (row, col), lane, INS_LOC site)` -- the INS_LOC ->
#: (block, lane) map is P1.T08d's, `evidence/hclk/mux38-138c.md` 2.
POINTS = [
    ("b5l1", (108, 117), 1, "BOTTOMSIDE[5]"),
    ("b5l2", (108, 117), 2, "BOTTOMSIDE[6]"),
    ("b5l3", (108, 117), 3, "BOTTOMSIDE[7]"),
    ("b4l0", (108, 64), 0, "BOTTOMSIDE[0]"),
    ("b4l2", (108, 64), 2, "BOTTOMSIDE[2]"),
]

RTL = """\
// Generated by evidence/dhcen/gate_probe.py (P1.T27) -- do not edit.
// One DHCE gating one CLKDIV on lane {lane} of block cell {block}.
`default_nettype none

module top (
    input  wire clk,
    input  wire reset,
    input  wire cen,
    output wire [3:0] led
);

    wire gated_clk;
    wire div_clk;

    DHCE gate0 (
        .CLKIN  (clk),
        .CEN    (cen),
        .CLKOUT (gated_clk)
    );

    CLKDIV div0 (
        .HCLKIN (gated_clk),
        .RESETN (reset),
        .CALIB  (1'b0),
        .CLKOUT (div_clk)
    );
    defparam div0.DIV_MODE = "4";

    reg [3:0] ring;
    always @(posedge div_clk)
        ring <= {{ring[2:0], ~ring[3]}};

    assign led = ring;

endmodule

`default_nettype wire
"""

#: Verbatim from the vendor-accepted `.cst` of batch `p1t38b-e2e`, whose
#: config-role claims carry their own MEASURED justification (P1.T08d).
CST = """\
// Generated by evidence/dhcen/gate_probe.py (P1.T27) -- do not edit.
// config-role pin V22 (EMCCLK) claimed on MEASURED evidence: EMCCLK: 27 vendor runs on this device placed a CLKDIV with clk on V22 and gw_sh returned 0 every time (P1.T08d evidence/hclk/mux38-138c.md 3); it is the Tang Mega 138K board clock and examples/gw5a/tangmega138k.cst names it
// config-role pin Y12 (SGCLK) claimed on MEASURED evidence: SGCLKC_6: a dedicated global-clock input ball, not a configuration function; same 27 P1.T08d runs used it as reset

IO_LOC  "clk" V22;
IO_PORT "clk" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
IO_LOC  "reset" Y12;
IO_PORT "reset" IO_TYPE=LVCMOS33 PULL_MODE=UP PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
IO_LOC  "cen" AA11;
IO_PORT "cen" IO_TYPE=LVCMOS33 PULL_MODE=UP PULL_STRENGTH=MEDIUM BANK_VCCIO=3.3;
IO_LOC  "led[0]" P20;
IO_PORT "led[0]" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM DRIVE=8 BANK_VCCIO=3.3;
IO_LOC  "led[1]" Y17;
IO_PORT "led[1]" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM DRIVE=8 BANK_VCCIO=3.3;
IO_LOC  "led[2]" W14;
IO_PORT "led[2]" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM DRIVE=8 BANK_VCCIO=3.3;
IO_LOC  "led[3]" Y16;
IO_PORT "led[3]" IO_TYPE=LVCMOS33 PULL_MODE=NONE PULL_STRENGTH=MEDIUM DRIVE=8 BANK_VCCIO=3.3;

INS_LOC "div0" {site};
"""

SDC = "create_clock -name clk -period 20 -waveform {0 10} [get_ports {clk}]\n"


def log(fh, msg):
    fh.write(f"{time.strftime('%H:%M:%S')} {msg}\n")
    fh.flush()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out-root", required=True)
    ap.add_argument("--log", required=True)
    ap.add_argument("--ledger", required=True)
    ap.add_argument("--budget", default=None)
    ap.add_argument("--pidfile", default=None)
    ap.add_argument("--points", default=",".join(p[0] for p in POINTS))
    args = ap.parse_args()

    wanted = [p for p in POINTS if p[0] in args.points.split(",")]
    fsdir = os.path.join(args.out_root, "fs")
    os.makedirs(fsdir, exist_ok=True)
    ok = aborted = 0

    with open(args.log, "a") as fh:
        if args.pidfile:
            open(args.pidfile, "w").write(str(os.getpid()) + "\n")
        log(fh, f"BATCH_START {BATCH_ID} runs={len(wanted)}")
        for name, block, lane, site in wanted:
            d = os.path.join(args.out_root, name)
            shutil.rmtree(d, ignore_errors=True)
            os.makedirs(d, exist_ok=True)
            open(os.path.join(d, "top.v"), "w").write(
                RTL.format(lane=lane, block=block))
            open(os.path.join(d, "top.cst"), "w").write(CST.format(site=site))
            open(os.path.join(d, "top.sdc"), "w").write(SDC)
            t0 = time.time()
            verdict, detail = "ok", ""
            try:
                res = oracle.run_oracle(d, timeout=1800)
                if not res["preflight"].ok:
                    verdict, detail = "refused", res["preflight"].reason
            except Exception as exc:                     # noqa: BLE001
                verdict, detail = "refused", f"{type(exc).__name__}: {exc}"
            wall = round(time.time() - t0, 1)
            fs = os.path.join(d, "run", "impl", "pnr", "run.fs")
            kept = None
            if os.path.isfile(fs):
                kept = os.path.join(fsdir, f"{name}.fs")
                shutil.copyfile(fs, kept)
            shutil.rmtree(os.path.join(d, "run"), ignore_errors=True)
            if verdict == "ok" and kept:
                ok += 1
            else:
                verdict, aborted = "refused", aborted + 1
            row = {"run_id": f"{BATCH_ID}-{name}", "shape": "dhce_gate_lane",
                   "primitive": "DHCE", "block": list(block), "lane": lane,
                   "ins_loc": site, "verdict": verdict, "wall_clock_s": wall,
                   "fs": kept, "detail": detail, "task": "P1.T27",
                   "device": DEVICE, "gowinhome": oracle.resolve_gowinhome(None),
                   "edu_provisional": False, "ts": time.time()}
            with open(args.ledger, "a") as lf:
                lf.write(json.dumps(row) + "\n")
            log(fh, f"RUN {name} block={block} lane={lane} verdict={verdict} "
                    f"wall={wall}s detail={detail[:120]}")
        if args.budget:
            with open(args.budget, "a") as bf:
                bf.write(f"{BATCH_ID}\tdhcen\t{len(wanted)}\t-\t"
                         f"{time.strftime('%Y-%m-%dT%H:%M:%S+00:00', time.gmtime())}\n")
        fh.write(f"BATCH_COMPLETE {BATCH_ID} runs={len(wanted)} ok={ok} "
                 f"diff=0 aborted={aborted}\n")
        fh.flush()
    return 0


if __name__ == "__main__":
    sys.exit(main())
