"""`P3.T11` -- the ODDR/ODDRC/IDDR/IDDRC attribute audit against the vendor.

What this measures, and with which instrument
---------------------------------------------
The question is *which IOLOGIC attributes the vendor actually sets* for each
of the four DDR gearbox primitives on the GW5AST-138C, and which of them
`gowin_pack` models today.  The instrument is the vendor bitstream, decoded
through apicula's own `IOLOGIC` shortval table:
`gowin_unpack.parse_attrvals` returns the **whole** `{attrid: attrval}` dict
the tile's fuses decode to -- not the two flags `gowin_unpack` goes on to
surface -- so an attribute the vendor sets and apicula's handler never emits
shows up as a key on the vendor side and nothing on the apicula side.

Why two runs and not four
-------------------------
`ODDRC` and `IDDRC` are their plain siblings plus a `CLEAR` port and no extra
parameter (`$GOWINHOME/IDE/simlib/gw5a/prim_sim.v:7793/7854/7988/8070`:
`ODDR`/`ODDRC` both carry `TXCLK_POL`+`INIT`, `IDDR`/`IDDRC` both carry
`Q0_INIT`+`Q1_INIT`), and one vendor design may carry two IOLOGIC instances on
two different balls.  So run `oddr-pair` carries `ODDR` **and** `ODDRC` and
run `iddr-pair` carries `IDDR` **and** `IDDRC`: four primitives measured
inside `P3.T11`'s two-run cap, each in its own IOLOGIC bel, told apart by the
`LSR*MUX_0` / `LSRMUX_LSR` reset attributes that are the C variants' whole
difference.

The HCLK-clocked variant the blueprint asks about is not run here, and that
is a measurement rather than an omission: `P3.T08` established `G-FCLK-138C`
-- this die has **no** HCLK->FCLK edge (`dev.io2hclk == {}`) and none of the
twelve vendor bitstreams `P3.T07` produced configures a single `FCLK*` pip.
The vendor clocks IOLOGIC on the 138C over `BUFG`/global, which is what both
runs here do.

Usage (from the apicula worktree, `PYTHONPATH=.`)::

    python $OTC/evidence/oddr-iddr/audit_oddr_iddr_attrs.py \\
        --design-root $DATASTORE/p3t11 --run all

`--run decode-only` re-derives the table from bitstreams already on disk and
spends no oracle run.
"""
import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

#: The two vendor designs, and the primitive each IOLOGIC instance carries.
#: Every ball is in `shapes/_io_base.SAFE_PINS`; `V22` is the board clock and
#: carries `io_basic`'s measured `EMCCLK` acknowledgement.
PLAN = (
    {"id": "oddr-pair", "primitives": {"ODDR": "AB16", "ODDRC": "AB17"}},
    {"id": "iddr-pair", "primitives": {"IDDR": "AA15", "IDDRC": "W15"}},
)

CLK_BALL = "V22"
RESET_BALL = "AB13"
DIN_A_BALL = "AA15"
DIN_B_BALL = "W15"
DOUT_A_BALL = "AB16"
DOUT_B_BALL = "AB17"

_ODDR_PAIR_RTL = """\
// Generated by $OTC/evidence/oddr-iddr/audit_oddr_iddr_attrs.py -- do not edit.
// P3.T11 attribute audit: ODDR and ODDRC in one design, both at the
// documented parameter defaults, both clocked from the board oscillator.
`default_nettype none

module top (
    input  wire clk,
    input  wire resetn,
    input  wire din,
    output wire dout_a,
    output wire dout_b
);

    reg  din_r;
    wire q0_a, q0_b;

    // A real producer for both gearboxes: an ODDR whose D0/D1 are constants
    // is folded away and the vendor then realises no IOLOGIC at all.
    always @(posedge clk)
        din_r <= din;

    ODDR dut_oddr (
        .D0  (din_r),
        .D1  (~din_r),
        .TX  (1'b0),
        .CLK (clk),
        .Q0  (q0_a),
        .Q1  ()
    );

    ODDRC dut_oddrc (
        .D0    (din_r),
        .D1    (~din_r),
        .TX    (1'b0),
        .CLK   (clk),
        .CLEAR (~resetn),
        .Q0    (q0_b),
        .Q1    ()
    );

    assign dout_a = q0_a;
    assign dout_b = q0_b;

endmodule

`default_nettype wire
"""

# The deserialiser's D comes straight off the pad: GowinSynthesis refuses a
# fabric flop between the two (`ERROR (CK0013)`, measured P3.T07), so both
# inputs are unregistered here and only the outputs carry fabric flops.
_IDDR_PAIR_RTL = """\
// Generated by $OTC/evidence/oddr-iddr/audit_oddr_iddr_attrs.py -- do not edit.
// P3.T11 attribute audit: IDDR and IDDRC in one design, both at the
// documented parameter defaults, both clocked from the board oscillator.
`default_nettype none

module top (
    input  wire clk,
    input  wire resetn,
    input  wire din_a,
    input  wire din_b,
    output wire dout_a,
    output wire dout_b
);

    wire q0_a, q1_a, q0_b, q1_b;
    reg  dout_ra, dout_rb;

    IDDR dut_iddr (
        .D   (din_a),
        .CLK (clk),
        .Q0  (q0_a),
        .Q1  (q1_a)
    );

    IDDRC dut_iddrc (
        .D     (din_b),
        .CLK   (clk),
        .CLEAR (~resetn),
        .Q0    (q0_b),
        .Q1    (q1_b)
    );

    always @(posedge clk) begin
        dout_ra <= q0_a ^ q1_a;
        dout_rb <= q0_b ^ q1_b;
    end

    assign dout_a = dout_ra;
    assign dout_b = dout_rb;

endmodule

`default_nettype wire
"""


def _shape(step):
    """An `IoShape` for one audit design, so it goes through the envelope."""
    from fuzz.gw5ast138c.shapes._io_base import IoShape
    from fuzz.gw5ast138c.shapes import io_basic

    outputs = step["id"] == "oddr-pair"
    ports = {
        "clk": (CLK_BALL, "input"),
        "resetn": (RESET_BALL, "input", {"pull_mode": "UP"}),
        "dout_a": (DOUT_A_BALL, "output"),
        "dout_b": (DOUT_B_BALL, "output"),
    }
    if outputs:
        ports["din"] = (DIN_A_BALL, "input")
    else:
        ports["din_a"] = (DIN_A_BALL, "input")
        ports["din_b"] = (DIN_B_BALL, "input")

    class AuditShape(IoShape):
        """One `P3.T11` audit design: two DDR gearboxes of the same direction."""

        name = "io_basic"          # the row this audit belongs to
        primitive = "/".join(step["primitives"])
        sweep_axis = "POINT"
        sweep_values = [step["id"]]
        baseline_value = step["id"]
        config_role_acks = io_basic.IoBasicShape.config_role_acks

        def __init__(self):
            self.ports = ports

        @property
        def clocks(self):
            return {"clk": 20.0}

        def rtl(self, sweep_value):
            return _ODDR_PAIR_RTL if outputs else _IDDR_PAIR_RTL

    return AuditShape().spec()


# --------------------------------------------------------------------------
# The vendor side: every attribute the bitstream's IOLOGIC tiles decode to
# --------------------------------------------------------------------------
_DB = None


def audit_db():
    """The one chipdb this audit reads -- the canonical `.msgpack.xz` (`F7`)."""
    global _DB
    if _DB is None:
        from fuzz.gw5ast138c.harness import equiv
        _DB = equiv.load_db()
    return _DB


def vendor_attrvals(fs_path):
    """`[{...}]`, one entry per realised IOLOGIC bel of a vendor bitstream.

    `gowin_unpack` surfaces only `MODE=` and `CLKODDRMUX_ECLK=` as flags; the
    audit needs the whole decoded `{attr: val}` dict, so `parse_attrvals` is
    called again here on the same tile with the same tables.
    """
    from apycula import attrids
    from apycula.gowin_unpack import parse_attrvals
    from fuzz.gw5ast138c.harness import equiv

    db = audit_db()
    netlist = equiv.unpack_netlist(fs_path, db=db)
    out = []
    for cell, flags in sorted(netlist.cells.items(),
                              key=lambda kv: (kv[0].y, kv[0].x, kv[0].z)):
        if cell.type != "IOLOGIC":
            continue
        row, col = cell.y, cell.x
        tile = netlist.tile_bitmap[(row, col)]
        ttyp = db[row, col].ttyp
        idx = "A" if cell.z == 0 else "B"
        table = db.shortval[ttyp].get(f"IOLOGIC{idx}")
        if table is None:
            continue
        raw = parse_attrvals(tile, db.rev_logicinfo("IOLOGIC"), table,
                             attrids.iologic_attrids, "IOLOGIC")
        # `parse_attrvals` keys its result by attribute NAME already; only
        # the value is still the table's numeric code.
        decoded = {attr: attrids.iologic_num2val.get(val, str(val))
                   for attr, val in sorted(raw.items())}
        out.append({
            "tile": [col, row],
            "vendor_bits": sorted(vendor_bits(tile, db, ttyp, idx)),
            "region_bits": len(region_coords(db, ttyp, idx)),
            "ttyp": ttyp,
            "idx": idx,
            "flags": sorted(flags),
            "mode": next((f.split("=", 1)[1] for f in flags
                          if f.startswith("MODE=")), None),
            "attrs": decoded,
        })
    return out


# --------------------------------------------------------------------------
# The apicula side: exactly what `gowin_pack` would emit for the same cell
# --------------------------------------------------------------------------
#: The `parms`/`attrs` `nextpnr`'s `pack_iologic.cc` puts on the packed cell
#: for each primitive at its documented defaults (`OUTMODE`/`INMODE` at
#: `pack_iologic.cc:130-141` and `:330-347`; the `C` variants are not
#: distinguished there and reach the packer as their plain siblings, so the
#: reset attribute is the only difference and it arrives as the cell type).
_PACKED = {
    "ODDR":  {"typ": "ODDR",  "parms": {"OUTMODE": "ODDRX1"}},
    "ODDRC": {"typ": "ODDRC", "parms": {"OUTMODE": "ODDRX1"}},
    "IDDR":  {"typ": "IDDR",  "parms": {"INMODE": "IDDRX1"}},
    "IDDRC": {"typ": "IDDRC", "parms": {"INMODE": "IDDRX1"}},
}


def apicula_attrvals(primitive, fclk="UNKNOWN"):
    """`{attr: val}` `GW5AST_138C` emits for `primitive`, today.

    The handlers read only the bel and the cell, so they are called on a bare
    instance: constructing a real `GW5AST_138C` needs a whole `nextpnr`
    netlist, and what is being audited is the handler, not the device.

    `fclk` defaults to `UNKNOWN` because that is what this die yields:
    `set_iologic_bel_fclk` maps `HCLK_OUT0..3` onto `SPINE10..13` and
    `G-FCLK-138C` (`P3.T08`) measured that the 138C has no HCLK->FCLK edge at
    all, so no 138C IOLOGIC cell ever carries an `IOLOGIC_FCLK` in that set.
    """
    from apycula import gowin_pack

    spec = _PACKED[primitive]

    class _Cell:
        typ = spec["typ"]
        parms = dict(spec["parms"])
        attrs = {}

    bel = gowin_pack.IologicBelDesc(0, 0, "0", _Cell(), fclk,
                                    spec["parms"].get("OUTMODE"),
                                    spec["parms"].get("INMODE"))
    device = object.__new__(gowin_pack.GW5AST_138C)
    attr_vals = device.common_iologic_handler(bel)
    if "OUTMODE" in spec["parms"]:
        attr_vals += device.get_out_iologic_attrs(bel)
    else:
        attr_vals += device.get_in_iologic_attrs(bel)
    return {av.attr: str(av.val) for av in attr_vals}


# --------------------------------------------------------------------------
# The bit-level half: what each side actually sets in the tile
# --------------------------------------------------------------------------
def _table(db, ttyp, idx):
    return db.shortval[ttyp][f"IOLOGIC{idx}"]


def region_coords(db, ttyp, idx):
    """Every fuse coordinate the tile's `IOLOGIC<idx>` table can reach.

    A bit outside it is some other bel's and is not this audit's business.
    """
    coords = set()
    for bits in _table(db, ttyp, idx).values():
        coords.update((abs(r), abs(c)) for r, c in bits)
    return coords


def fuse_bits(db, ttyp, idx, attrs):
    """The fuse set `gowin_pack` would write for `{attr: val}`.

    This is the packer's own path -- `add_attr_val` into the `IOLOGIC`
    logicinfo table, then `get_shortval_fuses` -- so a value the table does
    not carry contributes nothing here exactly as it would contribute nothing
    there.
    """
    from apycula import attrids
    from apycula.chipdb import add_attr_val, get_shortval_fuses

    av = set()
    for name, val in attrs.items():
        attr_id = attrids.iologic_attrids.get(name)
        val_id = attrids.iologic_attrvals.get(val)
        if attr_id is None or val_id is None:
            continue
        add_attr_val(db, "IOLOGIC", av, attr_id, val_id)
    return {tuple(bit) for bit in get_shortval_fuses(db, ttyp, av, f"IOLOGIC{idx}")}


def vendor_bits(tile, db, ttyp, idx):
    """The bits the vendor actually set inside this bel's fuse region."""
    return {(r, c) for r, c in region_coords(db, ttyp, idx) if tile[r][c] == 1}


# --------------------------------------------------------------------------
# The gap table
# --------------------------------------------------------------------------
#: Attributes apicula emits whose value is the literal string `UNKNOWN`.
#: These are not a modelling gap but an over-emission hazard: the value is a
#: real entry of `attrids.iologic_attrvals`, so it sets real fuses.
_UNKNOWN = "UNKNOWN"

TSV_HEADER = ("primitive\tattr\tvendor_val\tapicula_val\tdirection\tbits\t"
              "attrid\ttile\tttyp\tidx\tdisposition\tjustification")


def gap_rows(primitive, vendor, apicula):
    """One `attr-gap.tsv` row per attribute either side sets."""
    from apycula import attrids

    rows = []
    names = sorted(set(vendor["attrs"]) | set(apicula))
    for name in names:
        v = vendor["attrs"].get(name)
        a = apicula.get(name)
        if v is not None and a is None:
            direction, disposition = "vendor_only", "handler"
            why = ("the vendor sets it and gowin_pack does not emit it; "
                   "added to GW5AST_138C.common_iologic_handler by P3.T12")
        elif v is None and a is not None:
            direction = "apicula_only"
            if a == _UNKNOWN:
                disposition = "handler"
                why = ("apicula emits the literal UNKNOWN value, which sets "
                       "real fuses the vendor leaves clear; the 138C override "
                       "drops it (G-FCLK-138C: no HCLK->FCLK edge on this die)")
            else:
                disposition = "handler"
                why = ("gowin_pack emits it and the vendor does not; the "
                       "over-emission guard (equiv._residual_is_dirty) makes "
                       "this a DIFF, so the 138C override drops it")
        elif v != a:
            direction, disposition = "value_differs", "handler"
            why = f"vendor {v!r} vs gowin_pack {a!r}"
        else:
            direction, disposition = "agree", "unexplained-justified"
            why = "both sides set the same value; nothing to change"
        # How many fuses the disagreeing side's (attr, value) pair actually
        # moves.  An `apicula_only` entry worth zero bits is an encoding
        # artefact of the zero code, not an over-emission; one worth more is
        # a bit the vendor leaves clear and the over-emission guard fails on.
        db = audit_db()
        probe = a if a is not None and direction != "vendor_only" else v
        bits = len(fuse_bits(db, vendor["ttyp"], vendor["idx"],
                             {name: probe})) if probe else 0
        rows.append({
            "bits": bits,
            "primitive": primitive,
            "attr": name,
            "vendor_val": v if v is not None else "-",
            "apicula_val": a if a is not None else "-",
            "direction": direction,
            "attrid": attrids.iologic_attrids.get(name, "-"),
            "tile": "%d,%d" % tuple(vendor["tile"]),
            "ttyp": vendor["ttyp"],
            "idx": vendor["idx"],
            "disposition": disposition,
            "justification": why,
        })
    return rows


#: `P3.T06`'s measured ball -> cell table, the only thing that says which
#: package ball a decoded tile belongs to.
_PIN_TABLE = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "iologic", "pin-hclk-138c.json")


def ball_to_cell():
    """`{ball: (col, row, half)}` from `P3.T06`'s measured pin table."""
    with open(_PIN_TABLE) as fh:
        table = json.load(fh)
    return {p["ball"]: (p["col"], p["row"], p["half"]) for p in table["pins"]}


def match_vendor_cells(step, cells):
    """`{primitive: vendor cell or None}`, matched by **package ball**.

    Not by the decoded `MODE=` flag: `gowin_unpack` tells `ODDR` from `ODDRC`
    (and `IDDR` from `IDDRC`) by the mere *presence* of `LSROMUX_0` /
    `LSRIMUX_0` in the decoded set (`gowin_unpack.py:806-830`), and this die
    sets those attributes to `0` on the plain variants too -- so the flag
    mislabels a plain `ODDR` as `ODDRC`.  The ball each instance was placed on
    is in the vendor's own timing report and is unambiguous, so that is the
    key.
    """
    balls = ball_to_cell()
    by_site = {}
    for cell in cells:
        by_site[(cell["tile"][0], cell["tile"][1], cell["idx"])] = cell
    out = {}
    for primitive, ball in step["primitives"].items():
        col, row, half = balls[ball]
        out[primitive] = by_site.get((col, row, half))
    return out


def run_one(step, design_root, do_oracle=True):
    from fuzz.gw5ast138c.harness import gen, oracle

    design_dir = os.path.join(design_root, step["id"])
    spec = _shape(step)
    gen.run(spec, design_dir, step["id"])

    started = time.time()
    if do_oracle:
        result = oracle.run_oracle(design_dir, top_module="top")
        ok = result["preflight"].ok
        reason = result["preflight"].reason
        fs_path = result["artefacts"]["fs"][0] if ok else None
        log_path = result["log_path"]
    else:
        fs_path = os.path.join(design_dir, "run/impl/pnr/run.fs")
        ok = os.path.isfile(fs_path)
        reason = "decode-only" if ok else "no vendor .fs on disk"
        log_path = os.path.join(design_dir, "gw_sh.log")

    record = {
        "step": step["id"],
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "design_dir": design_dir,
        "vendor_fs": fs_path,
        "oracle_log": log_path if os.path.isfile(log_path) else None,
        "wall_clock_s": round(time.time() - started, 3),
        "ok": bool(ok),
        "reason": reason,
    }
    if not ok:
        record["cells"] = []
        return record
    record["cells"] = vendor_attrvals(fs_path)
    return record


def main(argv=None):
    parser = argparse.ArgumentParser(prog="audit_oddr_iddr_attrs")
    parser.add_argument("--design-root", required=True)
    parser.add_argument("--run", choices=("all", "decode-only"), default="all")
    parser.add_argument("--only", default=None)
    parser.add_argument("--out-dir", default=os.path.dirname(
        os.path.abspath(__file__)))
    args = parser.parse_args(argv)

    only = set(args.only.split(",")) if args.only else None
    records, rows, deltas = [], [], []
    for step in PLAN:
        if only and step["id"] not in only:
            continue
        record = run_one(step, args.design_root, do_oracle=args.run == "all")
        records.append(record)
        print("STEP %s ok=%s cells=%d" % (step["id"], record["ok"],
                                          len(record["cells"])), flush=True)
        if not record["ok"]:
            continue
        matched = match_vendor_cells(step, record["cells"])
        for primitive, vendor in matched.items():
            if vendor is None:
                print("  %s: NOT REALISED in this bitstream" % primitive)
                continue
            apicula = apicula_attrvals(primitive)
            rows.extend(gap_rows(primitive, vendor, apicula))
            # The verdict the over-emission guard will reach in P3.T12,
            # computed here from the same two fuse sets it compares.
            db = audit_db()
            mine = fuse_bits(db, vendor["ttyp"], vendor["idx"], apicula)
            theirs = {tuple(b) for b in vendor["vendor_bits"]}
            deltas.append({
                "primitive": primitive,
                "tile": vendor["tile"],
                "ttyp": vendor["ttyp"],
                "idx": vendor["idx"],
                "region_bits": vendor["region_bits"],
                "vendor_bits": sorted(theirs),
                "apicula_bits": sorted(mine),
                "over_emitted": sorted(mine - theirs),
                "missing": sorted(theirs - mine),
            })

    if deltas:
        with open(os.path.join(args.out_dir, "fuse-delta.json"), "w") as fh:
            json.dump(deltas, fh, indent=2, sort_keys=True)
            fh.write("\n")
        for delta in deltas:
            print("%-6s tile %s%s: vendor %d bits, gowin_pack %d, "
                  "over-emitted %d, missing %d"
                  % (delta["primitive"], delta["tile"], delta["idx"],
                     len(delta["vendor_bits"]), len(delta["apicula_bits"]),
                     len(delta["over_emitted"]), len(delta["missing"])))
    with open(os.path.join(args.out_dir, "audit-runs.json"), "w") as fh:
        json.dump(records, fh, indent=2, sort_keys=True)
        fh.write("\n")
    if rows:
        columns = TSV_HEADER.split("\t")
        with open(os.path.join(args.out_dir, "attr-gap.tsv"), "w") as fh:
            fh.write(TSV_HEADER + "\n")
            for row in rows:
                fh.write("\t".join(str(row[c]) for c in columns) + "\n")
    for row in rows:
        print("%-6s %-22s vendor=%-12s apicula=%-12s %s"
              % (row["primitive"], row["attr"], row["vendor_val"],
                 row["apicula_val"], row["direction"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
